### PR TITLE
template move to src

### PR DESCRIPTION
**Pull request by tophercf**
- move templates to src, for distribution and usage in shared package

### CODE REVIEW

**Review by robert-dean — COMMENTED** [review]
@tophercf What about moving these to src/templates/nestjs/... or maybe instead of in src at top level ./templates/.. We should be able to package that folder up then we can provide different templates as part of the package

**Comment by tophercf** [comment]
> @tophercf What about moving these to src/templates/nestjs/... or maybe instead of in src at top level ./templates/.. We should be able to package that folder up then we can provide different templates as part of the package

whatever you prefer - lmk

**Comment by tophercf** [comment]
templates are now top level, and copied into `dist`

**Pull request merged**
